version: '3.8'

services:

  #APP SERVER
  orsv1:
    container_name: orsv1-container
    build: .
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=23.251.144.25
      - DB_PORT=3309
      - DB_DATABASE=attendance_app
      - DB_USERNAME=root
      - DB_PASSWORD=root


    ports:
      - "8081:8081"
    command: ["php","artisan","serve","--host=0.0.0.0", "--port=8081"]
